#!/usr/bin/env python3
"""Finite-intervention Synergy Partition Trees for the frozen NYC Taxi MGSTN.

The search stage uses an affine transport-map readout of one shared empirical-product
intervention. The nonlinear dynamics are always generated by the accepted frozen MGSTN.
Selected splits are then diagnosed with held-out degree-2 transport maps after a
train-fit two-dimensional cross-covariance projection of each child coalition.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import os
import sys
import time
from itertools import combinations_with_replacement
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import torch
from matplotlib.colors import Normalize
from scipy.linalg import cholesky
from sklearn.decomposition import PCA
from threadpoolctl import threadpool_limits
from tqdm.auto import tqdm


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.analyze_runge_slp_pc60_xi_hierarchy import (  # noqa: E402
    ScalableHierarchyNode,
    _exact_candidates,
    _scalable_candidates,
    build_scalable_hierarchy,
    flatten_nodes,
)


TRAIN_SCRIPT = ROOT / "scripts/train_nyc_taxi_mgstn.py"
EI_SCRIPT = ROOT / "scripts/compute_nyc_taxi_mgstn_ei.py"
QUADRATIC_SCRIPT = ROOT / "scripts/compute_nyc_taxi_mgstn_quadratic_tm_full.py"
OUTPUT_DIR = ROOT / "results/nyc_taxi_mgstn_spt"
RUN_DIR = OUTPUT_DIR / "affine_regression_v3_time_block_search"
ACTIVE_PROGRESS = None
FIG_DIR = ROOT / "fig"
STATUS_PATH = ROOT / "docs/log/nyc_taxi_mgstn_spt_progress.json"
LOG_PATH = ROOT / "docs/log/nyc_taxi_mgstn_spt_run.log"

TIME_NAMES = ("recent", "daily", "weekly")
TIME_COLORS = {"recent": "#4C78A8", "daily": "#E69F63", "weekly": "#59A14F"}
DEFAULT_STATES = ("weekday_peak", "weekend_midday", "rainy_high_demand")
DEFAULT_SEEDS = (0, 1, 2)
AFFINE_TOLERANCE_BITS = 1.0e-8
QUADRATIC_TOLERANCE_BITS = 0.05
LOG2 = float(np.log(2.0))


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def atomic_json(path: Path, payload: Mapping[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    os.replace(temporary, path)


class Progress:
    def __init__(self, total: int):
        self.started = time.monotonic()
        self.total = int(total)
        self.current = 0
        self.last_write = 0.0

    def write(self, phase: str, *, metrics: Mapping[str, object] | None = None,
              message: str | None = None, force: bool = False) -> None:
        now = time.monotonic()
        if not force and now - self.last_write < 1.0:
            return
        elapsed = now - self.started
        rate = self.current / elapsed if elapsed > 0 and self.current else 0.0
        atomic_json(
            STATUS_PATH,
            {
                "phase": phase,
                "current": self.current,
                "total": self.total,
                "unit": "condition-stage",
                "elapsed_seconds": elapsed,
                "eta_seconds": None,  # Stages have different costs; no pooled-stage ETA.
                "metrics": dict(metrics or {}),
                "message": message,
                "updated_at": time.time(),
            },
        )
        self.last_write = now

    def advance(self, phase: str, *, metrics: Mapping[str, object] | None = None) -> None:
        self.current += 1
        self.write(phase, metrics=metrics, force=True)


def history_pools(flow: np.ndarray, times: np.ndarray) -> dict[str, np.ndarray]:
    recent_indices = times[:, None] - np.arange(7, 0, -1)[None, :]
    daily_indices = times[:, None] - 24 * np.arange(5, 0, -1)[None, :]
    weekly_indices = times[:, None] - 168 * np.arange(7, 0, -1)[None, :]
    return {
        "recent": flow[recent_indices].transpose(0, 2, 3, 1).astype(np.float32),
        "daily": flow[daily_indices].transpose(0, 2, 3, 1).astype(np.float32),
        "weekly": flow[weekly_indices].transpose(0, 2, 3, 1).astype(np.float32),
    }


def hurdle_features(raw: np.ndarray) -> np.ndarray:
    values = np.asarray(raw, dtype=np.float32)
    return np.concatenate([(values > 0).astype(np.float32), np.log1p(values)], axis=1)


def intervention_path(samples: int, components: int) -> Path:
    return OUTPUT_DIR / f"shared_intervention_n{samples}_pc{components}.npz"


def prepare_shared_intervention(training, data: dict, prepared: dict, split: dict,
                                *, samples: int, components: int, smoke: bool) -> dict[str, np.ndarray]:
    path = intervention_path(samples, components)
    if path.exists():
        saved = np.load(path, allow_pickle=False)
        return {key: saved[key] for key in saved.files}

    train_times = np.asarray(split["indices"]["train"], dtype=int)
    pools_z = history_pools(prepared["flow_z"], train_times)
    pools_raw = history_pools(data["flow"], train_times)
    zone_count = int(data["zone_ids"].shape[0])
    rng = np.random.default_rng(20260831)
    indices = {
        name: rng.integers(0, len(train_times), size=(samples, zone_count), dtype=np.int32)
        for name in TIME_NAMES
    }
    order = rng.permutation(samples)
    fit_n = int(round(0.70 * samples))
    fit_indices = np.sort(order[:fit_n]).astype(np.int32)
    evaluate_indices = np.sort(order[fit_n:]).astype(np.int32)
    histories: dict[str, np.ndarray] = {}
    atom_scores = np.empty((samples, zone_count * len(TIME_NAMES), components), dtype=np.float32)
    atom_explained = np.empty((zone_count * len(TIME_NAMES), components), dtype=np.float32)

    for time_index, name in enumerate(TIME_NAMES):
        width = pools_z[name].shape[-1]
        values_z = np.empty((samples, zone_count, 2, width), dtype=np.float32)
        for zone in range(zone_count):
            selected = indices[name][:, zone]
            values_z[:, zone] = pools_z[name][selected, zone]
            raw = pools_raw[name][selected, zone].reshape(samples, -1)
            features = hurdle_features(raw)
            pca = PCA(n_components=components, svd_solver="full")
            pca.fit(features[fit_indices])
            score = pca.transform(features).astype(np.float64)
            mean = score[fit_indices].mean(axis=0)
            scale = score[fit_indices].std(axis=0, ddof=1)
            if np.any(scale < 1.0e-8):
                raise RuntimeError(f"Degenerate hurdle PC for {name}, zone {zone}")
            score = (score - mean) / scale
            atom = zone * len(TIME_NAMES) + time_index
            atom_scores[:, atom] = score.astype(np.float32)
            atom_explained[atom] = pca.explained_variance_ratio_.astype(np.float32)
        histories[name] = values_z

    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        recent=histories["recent"],
        daily=histories["daily"],
        weekly=histories["weekly"],
        atom_scores=atom_scores,
        atom_explained=atom_explained,
        fit_indices=fit_indices,
        evaluate_indices=evaluate_indices,
        recent_indices=indices["recent"],
        daily_indices=indices["daily"],
        weekly_indices=indices["weekly"],
        zone_ids=data["zone_ids"].astype(np.int32),
        zone_names=data["zone_names"].astype(str),
    )
    return {
        "recent": histories["recent"], "daily": histories["daily"],
        "weekly": histories["weekly"], "atom_scores": atom_scores,
        "atom_explained": atom_explained, "fit_indices": fit_indices,
        "evaluate_indices": evaluate_indices, "zone_ids": data["zone_ids"].astype(np.int32),
        "zone_names": data["zone_names"].astype(str),
    }


def target_path(samples: int, seed: int, state: str) -> Path:
    return OUTPUT_DIR / f"targets/n{samples}/seed_{seed}/{state}.npz"


def predict_targets(training, ei, data: dict, prepared: dict, split: dict,
                    intervention: Mapping[str, np.ndarray], *, seed: int, state: str,
                    device: torch.device, batch_size: int) -> np.ndarray:
    path = target_path(len(intervention["atom_scores"]), seed, state)
    if path.exists():
        return np.load(path, allow_pickle=False)["target"].astype(np.float64)
    model, _ = ei.load_model(training, data, prepared["attributes_z"].shape[1], seed, device)
    centers = ei.select_centers(training, data, prepared, split, [state])
    center = {key: value for key, value in centers[0]["batch"].items() if key != "target"}
    samples = len(intervention["atom_scores"])
    outputs: list[np.ndarray] = []
    with torch.inference_mode():
        for start in range(0, samples, batch_size):
            stop = min(samples, start + batch_size)
            width = stop - start
            batch = {
                "recent": torch.from_numpy(intervention["recent"][start:stop]).to(device),
                "daily": torch.from_numpy(intervention["daily"][start:stop]).to(device),
                "weekly": torch.from_numpy(intervention["weekly"][start:stop]).to(device),
            }
            for key, value in center.items():
                if key in batch:
                    continue
                batch[key] = value.unsqueeze(0).expand(width, *value.shape).clone().to(device)
            outputs.append(model(batch).cpu().numpy().reshape(width, -1))
    target = np.concatenate(outputs).astype(np.float64)
    noise_covariance, noise_meta = ei.residual_covariance(training, model, prepared, split, device)
    noise = np.random.default_rng(910_000 + 1000 * seed + DEFAULT_STATES.index(state)).multivariate_normal(
        np.zeros(target.shape[1]), noise_covariance, size=samples
    )
    target += noise
    path.parent.mkdir(parents=True, exist_ok=True)
    stored_target = target.astype(np.float32)
    np.savez_compressed(path, target=stored_target, noise_metadata=np.asarray(json.dumps(noise_meta)))
    return stored_target.astype(np.float64)


class BlockConditionalOracle:
    """Cached affine-TM Xi values for two-dimensional source atoms."""

    def __init__(self, conditional: np.ndarray, atom_count: int, components: int):
        self.conditional = np.asarray(conditional, dtype=np.float64)
        self.atom_count = int(atom_count)
        self.components = int(components)
        self._ei_cache: dict[tuple[int, ...], float] = {}
        self._xi_cache: dict[tuple[int, ...], float] = {
            (index,): 0.0 for index in range(atom_count)
        }
        self.singletons = np.asarray([self.ei((index,)) for index in range(atom_count)])
        self.evaluations = atom_count
        self.last_progress = time.monotonic()

    def dimensions(self, indices: Iterable[int]) -> np.ndarray:
        return np.asarray(
            [dimension for atom in sorted(int(value) for value in indices)
             for dimension in range(atom * self.components, (atom + 1) * self.components)],
            dtype=int,
        )

    def ei(self, indices: Iterable[int]) -> float:
        key = tuple(sorted(int(value) for value in indices))
        if not key:
            return 0.0
        cached = self._ei_cache.get(key)
        if cached is not None:
            return cached
        dimensions = self.dimensions(key)
        factor = cholesky(self.conditional[np.ix_(dimensions, dimensions)], lower=True, check_finite=False)
        logdet = 2.0 * np.log(np.diag(factor)).sum()
        value = float(-0.5 * logdet / LOG2)
        self._ei_cache[key] = value
        return value

    def xi(self, indices: Iterable[int]) -> float:
        key = tuple(sorted(int(value) for value in indices))
        if not key:
            return 0.0
        cached = self._xi_cache.get(key)
        if cached is not None:
            return cached
        value = float(self.ei(key) - self.singletons[list(key)].sum())
        self._xi_cache[key] = value
        self.evaluations += 1
        if ACTIVE_PROGRESS is not None and time.monotonic() - self.last_progress > 5:
            ACTIVE_PROGRESS.write("affine_search", metrics={"coalitions": self.evaluations}, force=True)
            self.last_progress = time.monotonic()
        return value


def fit_affine_oracle(atom_scores: np.ndarray, target: np.ndarray, fit_indices: np.ndarray,
                      *, target_ridge: float
                      ) -> tuple[BlockConditionalOracle, dict[str, float], np.ndarray]:
    x = atom_scores[fit_indices].reshape(len(fit_indices), -1).astype(np.float64)
    y = target[fit_indices].astype(np.float64)
    y_mean = y.mean(axis=0)
    y_scale = y.std(axis=0, ddof=1)
    if np.any(y_scale < 1.0e-8):
        raise RuntimeError("Degenerate MGSTN target dimension")
    y = (y - y_mean) / y_scale
    x = x - x.mean(axis=0)
    if len(x) <= x.shape[1]:
        raise ValueError("Affine regression requires more fit samples than source dimensions")
    cross, _, rank, _ = np.linalg.lstsq(x, y, rcond=None)
    if rank != x.shape[1]:
        raise RuntimeError(f"Rank-deficient affine source design: {rank}/{x.shape[1]}")
    residual = y - x @ cross
    residual_covariance = residual.T @ residual / (len(x) - 1)
    residual_covariance += float(target_ridge) * np.eye(y.shape[1])
    # Coherent Gaussian affine-TM readout: X~N(0,I), Y=X B+epsilon.
    # Do not combine the identity source prior with an unrelated empirical Y covariance.
    target_covariance = cross.T @ cross + residual_covariance
    explained = cross @ np.linalg.solve(target_covariance, cross.T)
    conditional = np.eye(x.shape[1]) - explained
    conditional = 0.5 * (conditional + conditional.T)
    eigenvalues = np.linalg.eigvalsh(conditional)
    audit = {
        "conditional_min_eigenvalue": float(eigenvalues.min()),
        "conditional_max_eigenvalue": float(eigenvalues.max()),
        "target_condition_number": float(np.linalg.cond(target_covariance)),
        "design_rank": int(rank),
        "training_variance_explained": float(1 - np.sum(residual**2) / np.sum(y**2)),
        "residual_min_eigenvalue": float(np.linalg.eigvalsh(residual_covariance).min()),
    }
    if eigenvalues.min() <= 0.0:
        raise RuntimeError(
            f"Affine conditional covariance is not positive definite: min={eigenvalues.min():.6g}"
        )
    return BlockConditionalOracle(conditional, atom_scores.shape[1], atom_scores.shape[2]), audit, cross


def pair_affinity(oracle: BlockConditionalOracle, atom_count: int) -> tuple[np.ndarray, int, float]:
    affinity = np.zeros((atom_count, atom_count), dtype=np.float64)
    tolerance_zero = 0
    minimum = math.inf
    for left in range(atom_count):
        for right in range(left + 1, atom_count):
            value = oracle.xi((left, right))
            minimum = min(minimum, value)
            if value < -AFFINE_TOLERANCE_BITS:
                raise RuntimeError(
                    f"Pair Syn nonnegativity violation: {value:.12g} bits; "
                    f"threshold={-AFFINE_TOLERANCE_BITS}; affected_count=1"
                )
            if value < 0.0:
                tolerance_zero += 1
                value = 0.0
            affinity[left, right] = affinity[right, left] = value
    return affinity, tolerance_zero, float(minimum)


def audit_nonnegative(values, tolerance: float, context: str) -> dict:
    values = np.asarray(values, dtype=float)
    if not np.all(np.isfinite(values)):
        raise RuntimeError(f"{context}: nonfinite Syn")
    minimum = float(values.min())
    affected = int(np.sum(values < -tolerance))
    if affected:
        raise RuntimeError(f"{context}: Syn nonnegativity violation; minimum={minimum:.12g} bits; "
                           f"threshold={-tolerance}; affected_count={affected}")
    return {"minimum_bits": minimum, "tolerance_zero_count": int(np.sum(values < 0)),
            "violation_count": affected, "tolerance_bits": tolerance}


def build_time_prior_tree(oracle: BlockConditionalOracle, affinity: np.ndarray, *, exact_max_size: int,
                          audit: dict[str, int]) -> ScalableHierarchyNode:
    """Build an SPT constrained to intact time blocks at the first two levels.

    The root optimizer compares the three legal time-block bipartitions. It does
    not prescribe which scale is isolated. The selected two-scale block is then
    refined into its two intact scales, after which each scale receives an
    independently searched spatial SPT.
    """
    groups = {
        name: tuple(zone * 3 + TIME_NAMES.index(name) for zone in range(oracle.atom_count // 3))
        for name in TIME_NAMES
    }
    all_indices = tuple(range(oracle.atom_count))
    all_xi = oracle.xi(all_indices)
    candidates = []
    for isolated_name in TIME_NAMES:
        paired_names = tuple(name for name in TIME_NAMES if name != isolated_name)
        paired_indices = tuple(sorted(groups[paired_names[0]] + groups[paired_names[1]]))
        captured = oracle.xi(groups[isolated_name]) + oracle.xi(paired_indices)
        residual = float(all_xi - captured)
        nonnegative = audit_nonnegative(
            [residual], AFFINE_TOLERANCE_BITS, f"time-block root {isolated_name} | {paired_names}"
        )
        audit["candidate_count"] += 1
        audit["tolerance_zero_count"] += nonnegative["tolerance_zero_count"]
        candidates.append((captured, -residual, isolated_name, paired_names, paired_indices, residual))
    _, _, isolated_name, paired_names, paired_indices, root_syn = max(
        candidates, key=lambda row: (row[0], row[1], row[2])
    )

    subtree_depth = {name: (1 if name == isolated_name else 2) for name in TIME_NAMES}
    subtrees = {
        name: build_scalable_hierarchy(
            groups[name], oracle, affinity, exact_max_size=exact_max_size,
            tolerance=AFFINE_TOLERANCE_BITS, depth=subtree_depth[name], audit=audit,
        ) for name in TIME_NAMES
    }
    macro_syn = float(
        oracle.xi(paired_indices)
        - oracle.xi(groups[paired_names[0]])
        - oracle.xi(groups[paired_names[1]])
    )
    macro_audit = audit_nonnegative(
        [macro_syn], AFFINE_TOLERANCE_BITS, f"time-block refinement {paired_names}"
    )
    audit["tolerance_zero_count"] += macro_audit["tolerance_zero_count"]
    macro = ScalableHierarchyNode(
        paired_indices, oracle.xi(paired_indices), macro_syn, 1, "time-block-refinement",
        tuple(subtrees[name] for name in paired_names),
    )
    return ScalableHierarchyNode(
        all_indices, all_xi, root_syn, 0, "time-block-search",
        (subtrees[isolated_name], macro),
    )


def tree_metrics(root: ScalableHierarchyNode) -> dict[str, float | int]:
    nodes = flatten_nodes(root)
    internal = [node for node in nodes if node.children]
    leaves = [node for node in nodes if not node.children]
    depths = [node.depth for node in leaves]

    def spine_length(node: ScalableHierarchyNode) -> int:
        count = 0
        current = node
        while current.children:
            count += 1
            current = max(current.children, key=lambda child: (child.size, -min(child.indices)))
        return count

    purity = []
    for node in internal:
        counts = np.bincount([index % 3 for index in node.indices], minlength=3)
        purity.append(float(counts.max() / node.size))
    raw_syn = np.asarray([node.syn_bits for node in internal])
    audit_nonnegative(raw_syn, AFFINE_TOLERANCE_BITS, "tree metric weights")
    weights = np.where(raw_syn < 0, 0., raw_syn)
    return {
        "internal_node_count": len(internal),
        "maximum_depth": int(max(depths)),
        "mean_leaf_depth": float(np.mean(depths)),
        "dominant_spine_split_count": spine_length(root),
        "dominant_spine_fraction": float(spine_length(root) / max(1, len(internal))),
        "mean_internal_time_purity": float(np.mean(purity)),
        "syn_weighted_time_purity": float(
            np.average(purity, weights=weights) if weights.sum() else np.mean(purity)
        ),
        "same_zone_recent_weekly_pair_count": sum(
            n.size == 2 and n.indices[0] // 3 == n.indices[1] // 3
            and {i % 3 for i in n.indices} == {0, 2} for n in internal),
        "pair_syn_fraction": float(sum(n.syn_bits for n in internal if n.size == 2) / root.xi_bits),
        "top_time_partition_syn_fraction": float(sum(
            n.syn_bits for n in internal if n.search_kind in {"time-block-search", "time-block-refinement"}
        ) / root.xi_bits),
    }


def serialize_tree(node: ScalableHierarchyNode, zone_ids: np.ndarray) -> dict[str, object]:
    counts = {name: int(sum(index % 3 == position for index in node.indices))
              for position, name in enumerate(TIME_NAMES)}
    members = [
        {"atom": int(index), "zone_id": int(zone_ids[index // 3]), "time": TIME_NAMES[index % 3]}
        for index in node.indices
    ]
    return {
        "indices": list(node.indices), "size": node.size, "xi_bits": float(node.xi_bits),
        "syn_bits": float(node.syn_bits), "depth": int(node.depth),
        "search_kind": node.search_kind, "time_counts": counts, "members": members,
        "children": [serialize_tree(child, zone_ids) for child in node.children],
    }


def time_block_split_metadata(root: ScalableHierarchyNode) -> dict[str, object]:
    if root.search_kind != "time-block-search" or len(root.children) != 2:
        raise ValueError("Expected a time-block-search root")
    isolated, paired = root.children
    isolated_scales = sorted({TIME_NAMES[index % 3] for index in isolated.indices})
    paired_scales = sorted({TIME_NAMES[index % 3] for index in paired.indices})
    if len(isolated_scales) != 1 or len(paired_scales) != 2:
        raise RuntimeError("Time-block SPT violated the intact-scale constraint")
    return {
        "selected_root_split": [isolated_scales, paired_scales],
        "root_syn_bits": float(root.syn_bits),
        "paired_block_refinement_syn_bits": float(paired.syn_bits),
        "selection_rule": "maximize child Xi sum among the three intact time-block bipartitions",
    }


def deserialize_tree(payload: Mapping[str, object]) -> ScalableHierarchyNode:
    return ScalableHierarchyNode(
        tuple(int(value) for value in payload["indices"]), float(payload["xi_bits"]),
        float(payload["syn_bits"]), int(payload["depth"]), str(payload["search_kind"]),
        tuple(deserialize_tree(child) for child in payload.get("children", [])),
    )


def closure_error(root: ScalableHierarchyNode) -> float:
    return float(root.xi_bits - sum(node.syn_bits for node in flatten_nodes(root) if node.children))


def condition_dir(seed: int, state: str) -> Path:
    return RUN_DIR / f"seed_{seed}/{state}"


def run_affine_condition(intervention: Mapping[str, np.ndarray], target: np.ndarray, *, seed: int,
                         state: str, target_ridge: float,
                         exact_max_size: int) -> dict[str, object]:
    out = condition_dir(seed, state)
    summary_path = out / "affine_summary.json"
    signature = hashlib.sha256(intervention["atom_scores"].tobytes() + target.tobytes()).hexdigest()
    if summary_path.exists():
        cached = json.loads(summary_path.read_text(encoding="utf-8"))
        if signature not in (cached.get("input_sha256"), cached.get("verified_roundtrip_input_sha256")):
            raise RuntimeError("Cached affine inputs differ from this run")
        for name in ("unconstrained", "time_prior"):
            cached[name]["tree_metrics"] = tree_metrics(deserialize_tree(cached[name]["tree"]))
        return cached
    started = time.monotonic()
    oracle, covariance_audit, cross = fit_affine_oracle(
        intervention["atom_scores"], target, intervention["fit_indices"].astype(int),
        target_ridge=target_ridge,
    )
    affinity, pair_zero, pair_minimum = pair_affinity(oracle, oracle.atom_count)
    mixed_audit = {"candidate_count": 0, "tolerance_zero_count": 0}
    mixed = build_scalable_hierarchy(
        tuple(range(oracle.atom_count)), oracle, affinity, exact_max_size=exact_max_size,
        tolerance=AFFINE_TOLERANCE_BITS, audit=mixed_audit,
    )
    prior_audit = {"candidate_count": 0, "tolerance_zero_count": 0}
    prior = build_time_prior_tree(oracle, affinity, exact_max_size=exact_max_size, audit=prior_audit)
    for name, tree in (("unconstrained", mixed), ("time_prior", prior)):
        audit_nonnegative([node.syn_bits for node in flatten_nodes(tree) if node.children],
                          AFFINE_TOLERANCE_BITS, name)
        error = closure_error(tree)
        if abs(error) > 1.0e-7:
            raise RuntimeError(f"{name} SPT closure failed: {error:.12g} bits")
    out.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out / "affine_cache.npz", conditional=oracle.conditional, affinity=affinity, cross=cross)
    summary = {
        "seed": seed, "state": state, "samples": int(len(target)),
        "source_atoms": int(oracle.atom_count), "components_per_atom": int(oracle.components),
        "target_dimension": int(target.shape[1]), "target_ridge": target_ridge,
        "estimator": "generative_affine_tm_v2",
        "exact_max_size": exact_max_size,
        "input_sha256": signature,
        "elapsed_seconds": time.monotonic() - started,
        "nonnegative_tolerance_bits": AFFINE_TOLERANCE_BITS,
        "pair_minimum_syn_bits": pair_minimum, "pair_tolerance_zero_count": pair_zero,
        "covariance_audit": covariance_audit, "coalition_evaluation_count": oracle.evaluations,
        "unconstrained": {
            "candidate_split_count": mixed_audit["candidate_count"],
            "split_tolerance_zero_count": mixed_audit["tolerance_zero_count"],
            "closure_error_bits": closure_error(mixed), "tree_metrics": tree_metrics(mixed),
            "tree": serialize_tree(mixed, intervention["zone_ids"]),
        },
        "time_prior": {
            "candidate_split_count": prior_audit["candidate_count"],
            "split_tolerance_zero_count": prior_audit["tolerance_zero_count"],
            "closure_error_bits": closure_error(prior), "tree_metrics": tree_metrics(prior),
            "time_block_search": time_block_split_metadata(prior),
            "tree": serialize_tree(prior, intervention["zone_ids"]),
        },
    }
    atomic_json(summary_path, summary)
    return summary


def child_crosscov_scores(atom_scores: np.ndarray, target: np.ndarray, fit_indices: np.ndarray,
                           coalition: Sequence[int], components: int = 2) -> np.ndarray:
    dimensions = [dimension for atom in coalition for dimension in (atom * 2, atom * 2 + 1)]
    x = atom_scores.reshape(len(atom_scores), -1)[:, dimensions].astype(np.float64)
    y = target.astype(np.float64)
    xf = x[fit_indices] - x[fit_indices].mean(axis=0)
    yf = y[fit_indices] - y[fit_indices].mean(axis=0)
    cross = xf.T @ yf / (len(fit_indices) - 1)
    u, _, _ = np.linalg.svd(cross, full_matrices=False)
    width = min(components, u.shape[1])
    projected = (x - x[fit_indices].mean(axis=0)) @ u[:, :width]
    if width < components:
        projected = np.column_stack([projected, np.zeros((len(x), components - width))])
    mean = projected[fit_indices].mean(axis=0)
    scale = projected[fit_indices].std(axis=0, ddof=1)
    scale[scale < 1.0e-8] = 1.0
    return ((projected - mean) / scale).astype(np.float64)


def selected_splits(root: ScalableHierarchyNode) -> list[tuple[tuple[int, ...], tuple[int, ...], float, int]]:
    rows = []
    for node in flatten_nodes(root):
        if not node.children:
            continue
        rows.append((node.children[0].indices, node.children[1].indices, float(node.syn_bits), node.size))
    return rows


def polynomial_conditional_log_prob(prefix, right, fit, evaluate, *, ridge: float, degree: int = 2):
    """Exact conditional factors of the existing polynomial triangular TM.

    Only right-hand factors enter CMI. Unused prefix densities cancel, so we avoid
    fitting them. Explicit quadratic products replace the generic exponent tensor.
    Ordering, sample SD, residual floor and intercept-unpenalized ridge are unchanged.
    """
    output = np.zeros(len(evaluate), dtype=float)
    for dimension in range(right.shape[1]):
        predictors = np.column_stack([prefix, right[:, :dimension]])
        mean = predictors[fit].mean(axis=0)
        scale = predictors[fit].std(axis=0, ddof=1)
        scale = np.where(scale > 1e-8, scale, 1.0)
        z = (predictors - mean) / scale
        columns = [np.ones(len(z))] + [z[:, j] for j in range(z.shape[1])]
        if degree == 2:
            columns += [z[:, j] * z[:, k] for j, k in combinations_with_replacement(range(z.shape[1]), 2)]
        design = np.column_stack(columns)
        training = design[fit]
        gram = training.T @ training + ridge * np.eye(training.shape[1])
        gram[0, 0] -= ridge
        coefficients = np.linalg.solve(gram, training.T @ right[fit, dimension])
        residual_scale = max(float((right[fit, dimension] - training @ coefficients).std(ddof=1)), 1e-8)
        standardized = (right[evaluate, dimension] - design[evaluate] @ coefficients) / residual_scale
        output += -.5 * (np.log(2*np.pi) + standardized**2) - np.log(residual_scale)
    return output


class FastQuadraticTM:
    @staticmethod
    def estimate_quadratic_cmi(left, right, target, fit_indices, evaluate_indices, *, ridge):
        full = polynomial_conditional_log_prob(np.column_stack([target, left]), right,
                                               fit_indices, evaluate_indices, ridge=ridge)
        reduced = polynomial_conditional_log_prob(target, right, fit_indices, evaluate_indices, ridge=ridge)
        pointwise = (full - reduced) / LOG2
        return {"syn_bits_raw": float(pointwise.mean()),
                "syn_bits_se": float(pointwise.std(ddof=1) / np.sqrt(len(pointwise))),
                "evaluation_samples": int(len(pointwise))}


def quadratic_split_jobs(summary: dict, *, seed: int, state: str, tree_names: Sequence[str]) -> list[dict]:
    cache = np.load(condition_dir(seed, state) / "affine_cache.npz")
    oracle = BlockConditionalOracle(cache["conditional"], summary["source_atoms"], 2)
    jobs = []
    for tree_name in tree_names:
        root = deserialize_tree(summary[tree_name]["tree"])
        nodes = [node for node in flatten_nodes(root) if node.children]
        # Prespecified budget: two runner-ups at the eight strongest non-fixed nodes.
        ranked = sorted([node for node in nodes if not node.search_kind.startswith("time-block") and node.size > 2],
                        key=lambda node: node.syn_bits, reverse=True)[:8]
        for node_index, node in enumerate(nodes):
            left, right = (child.indices for child in node.children)
            jobs.append(dict(tree=tree_name, node_index=node_index, node_size=node.size,
                             left=list(left), right=list(right), affine_syn_bits=node.syn_bits,
                             role="selected"))
            if node.search_kind == "time-block-search":
                groups = {name: tuple(index for index in node.indices if index % 3 == position)
                          for position, name in enumerate(TIME_NAMES)}
                selected = {tuple(left), tuple(right)}
                alternatives = []
                for isolated_name in TIME_NAMES:
                    a = groups[isolated_name]
                    b = tuple(sorted(index for name in TIME_NAMES if name != isolated_name for index in groups[name]))
                    if {a, b} == selected:
                        continue
                    value = oracle.xi(node.indices) - oracle.xi(a) - oracle.xi(b)
                    audit_nonnegative([value], AFFINE_TOLERANCE_BITS, "time-block runner-up split")
                    alternatives.append((value, a, b))
                for rank, (value, a, b) in enumerate(sorted(alternatives), 1):
                    jobs.append(dict(tree=tree_name, node_index=node_index, node_size=node.size,
                                     left=list(a), right=list(b), affine_syn_bits=value,
                                     role=f"time_block_runner_up_{rank}"))
                continue
            if node.search_kind == "time-block-refinement":
                continue
            if node not in ranked:
                continue
            candidates = (_exact_candidates(node.indices) if node.size <= summary.get("exact_max_size", 8) else
                          _scalable_candidates(node.indices, cache["affinity"]))
            alternatives = []
            for a, b in candidates:
                if {a, b} == {left, right}:
                    continue
                value = oracle.xi(node.indices) - oracle.xi(a) - oracle.xi(b)
                audit_nonnegative([value], AFFINE_TOLERANCE_BITS, "runner-up split")
                alternatives.append((value, a, b))
            for rank, (value, a, b) in enumerate(sorted(alternatives)[:2], 1):
                jobs.append(dict(tree=tree_name, node_index=node_index, node_size=node.size,
                                 left=list(a), right=list(b), affine_syn_bits=value,
                                 role=f"runner_up_{rank}"))
    return jobs


def validate_quadratic_condition(intervention: Mapping[str, np.ndarray], target: np.ndarray, summary: dict,
                                 quadratic, *, seed: int, state: str, ridge: float,
                                 tree_names: Sequence[str]) -> dict[str, object]:
    out = condition_dir(seed, state) / f"quadratic_validation_r{ridge:g}.json"
    if out.exists():
        cached = json.loads(out.read_text(encoding="utf-8"))
        if cached["status"] == "passed":
            return cached
        raise RuntimeError(f"Quadratic audit previously failed; inspect {out}")
    fit = intervention["fit_indices"].astype(int)
    evaluate = intervention["evaluate_indices"].astype(int)
    score_cache: dict[tuple[int, ...], np.ndarray] = {}

    def scores(indices: tuple[int, ...]) -> np.ndarray:
        key = tuple(sorted(indices))
        if key not in score_cache:
            score_cache[key] = child_crosscov_scores(
                intervention["atom_scores"], target, fit, key, components=2
            )
        return score_cache[key]

    records = []
    jobs = quadratic_split_jobs(summary, seed=seed, state=state, tree_names=tree_names)
    started = time.monotonic()
    payload = {
        "seed": seed, "state": state, "ridge": ridge,
        "status": "running", "planned_records": len(jobs),
        "estimator": "degree-2 TM after train-fit two-crosscov-direction projection of hurdle PCs",
        "target_semantics": "66 target-wise projected CMI diagnostics; not full-coalition or joint-target Syn",
        "nonnegative_tolerance_bits": QUADRATIC_TOLERANCE_BITS,
        "records": records,
    }
    for number, job in enumerate(tqdm(jobs, desc=f"Projected TM seed={seed} {state}", unit="split")):
        left, right = tuple(job["left"]), tuple(job["right"])
        key = hashlib.sha256(json.dumps([left, right, ridge, summary["input_sha256"], "projection_v2"]).encode()).hexdigest()[:24]
        split_path = out.parent / "quadratic_splits" / f"{key}.json"
        if split_path.exists():
            estimates = json.loads(split_path.read_text())
        else:
            left_scores, right_scores = scores(left), scores(right)
            estimates = {"zone_values_bits": [], "zone_standard_errors_bits": []}
            for zone in range(target.shape[1] // 2):
                result = quadratic.estimate_quadratic_cmi(
                    left_scores, right_scores, target[:, 2 * zone:2 * zone + 2], fit, evaluate, ridge=ridge)
                estimates["zone_values_bits"].append(float(result["syn_bits_raw"]))
                estimates["zone_standard_errors_bits"].append(float(result["syn_bits_se"]))
            atomic_json(split_path, estimates)
        values = np.asarray(estimates["zone_values_bits"])
        records.append(job | estimates | {
            "quadratic_targetwise_sum_bits": float(values.sum()),
            "quadratic_min_zone_bits": float(values.min()),
            "quadratic_negative_zone_count": int(np.sum(values < 0)),
            "quadratic_violation_zone_count": int(np.sum(values < -QUADRATIC_TOLERANCE_BITS)),
        })
        payload["minimum_zone_syn_bits"] = min(row["quadratic_min_zone_bits"] for row in records)
        payload["node_with_any_violation_count"] = sum(row["quadratic_violation_zone_count"] > 0 for row in records)
        payload["elapsed_seconds"] = time.monotonic() - started
        try:
            audit_nonnegative(values, QUADRATIC_TOLERANCE_BITS, f"projected quadratic {seed}/{state}/{number}")
        except RuntimeError as error:
            payload.update(status="failed", error=str(error))
            atomic_json(out, payload)
            raise
        if ACTIVE_PROGRESS is not None:
            ACTIVE_PROGRESS.write("quadratic_diagnostic", metrics={"seed": seed, "state": state,
                                  "completed_splits": number + 1, "total_splits": len(jobs),
                                  "phase_eta_seconds": payload["elapsed_seconds"] / (number + 1) * (len(jobs)-number-1)})
    payload["status"] = "passed"
    atomic_json(out, payload)
    return payload


def leaf_order(root: ScalableHierarchyNode) -> list[int]:
    if not root.children:
        return [root.indices[0]]
    return [index for child in root.children for index in leaf_order(child)]


def tree_positions(root: ScalableHierarchyNode) -> dict[tuple[int, ...], tuple[float, float]]:
    order = leaf_order(root)
    leaf_x = {atom: float(position) for position, atom in enumerate(order)}
    positions: dict[tuple[int, ...], tuple[float, float]] = {}

    def visit(node: ScalableHierarchyNode) -> tuple[float, float]:
        if not node.children:
            point = (leaf_x[node.indices[0]], 0.0)
        else:
            child_points = [visit(child) for child in node.children]
            x = sum(point[0] * child.size for point, child in zip(child_points, node.children, strict=True)) / node.size
            point = (x, math.log2(node.size) / math.log2(root.size))
        positions[node.indices] = point
        return point

    visit(root)
    return positions


def plot_tree(axis, root: ScalableHierarchyNode, *, label: str, zone_ids: np.ndarray,
              norm: Normalize) -> None:
    positions = tree_positions(root)
    internal = [node for node in flatten_nodes(root) if node.children]
    audit_nonnegative([node.syn_bits for node in internal], AFFINE_TOLERANCE_BITS, "figure")
    cmap = mpl.colormaps["YlGnBu"]
    for node in internal:
        parent = positions[node.indices]
        children = [positions[child.indices] for child in node.children]
        axis.plot([children[0][0], children[1][0]], [parent[1], parent[1]], color="#B7C0C8", lw=0.45, zorder=1)
        for child in children:
            axis.plot([child[0], child[0]], [child[1], parent[1]], color="#B7C0C8", lw=0.45, zorder=1)
        # Audit above rejects significant negatives; only tolerance-scale negatives
        # are displayed at zero. Cached raw Syn values are never changed.
        display_syn = 0.0 if node.syn_bits < 0 else node.syn_bits
        axis.scatter([parent[0]], [parent[1]], s=5 + 24 * norm(display_syn),
                     c=[cmap(norm(display_syn))], edgecolors="#35515D", lw=0.3, zorder=3)
    order = leaf_order(root)
    for position, atom in enumerate(order):
        axis.scatter([position], [0], s=8, color=TIME_COLORS[TIME_NAMES[atom % 3]],
                     edgecolors="white", lw=0.25, zorder=4)
    if root.search_kind == "time-block-search":
        for node in internal:
            if node.size == 66 and len({i % 3 for i in node.indices}) == 1:
                x, y = positions[node.indices]
                time_name = TIME_NAMES[node.indices[0] % 3]
                axis.text(x, y + .025, f"{time_name} (66 zones)", ha="center", va="bottom",
                          fontsize=8, color=TIME_COLORS[time_name])
    axis.text(0.0, 1.02, label, transform=axis.transAxes, ha="left", va="bottom", fontsize=8.0, color="#24313C")
    axis.set_xlim(-2, root.size + 1)
    axis.set_ylim(-0.015, 1.04)
    axis.set_xticks(range(len(order)), [f"{zone_ids[i//3]} {'RDW'[i%3]}" for i in order], rotation=90, fontsize=5)
    axis.tick_params(axis="x", length=0, pad=3)
    axis.set_xlabel("Source atoms: Taxi Zone ID × time scale (R: recent; D: daily; W: weekly)", labelpad=8)
    axis.set_ylabel("Coalition size (log scale)")
    ticks = [1, 2, 4, 8, 16, 32, 66, 132, 198]
    axis.set_yticks(np.log2(ticks) / np.log2(root.size), [str(t) for t in ticks])
    axis.spines[["top", "right", "bottom"]].set_visible(False)


def representative_condition(summaries: Sequence[dict]) -> tuple[int, str]:
    values = np.asarray([row["unconstrained"]["tree"]["xi_bits"] for row in summaries], dtype=float)
    index = int(np.argmin(np.abs(values - values.mean())))
    return int(summaries[index]["seed"]), str(summaries[index]["state"])


def plot_figures(summaries: Sequence[dict], conditions: Sequence[tuple[int, str]]) -> list[Path]:
    mpl.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
        "font.size": 6.5, "axes.linewidth": 0.7, "svg.fonttype": "none",
        "savefig.facecolor": "white",
    })
    seed, state = representative_condition(summaries)
    chosen = next(row for row in summaries if row["seed"] == seed and row["state"] == state)
    roots = {name: deserialize_tree(chosen[name]["tree"]) for name in ("unconstrained", "time_prior")}
    norm = mpl.colors.SymLogNorm(linthresh=.001, linscale=.5, vmin=0,
            vmax=max(n.syn_bits for root in roots.values() for n in flatten_nodes(root)), base=10)
    zone_ids = np.array([chosen["unconstrained"]["tree"]["members"][i*3]["zone_id"] for i in range(66)])
    outputs = []
    for tree_name, suffix in (("unconstrained", "unconstrained"), ("time_prior", "time_prior")):
        root = roots[tree_name]
        figure, tree_axis = plt.subplots(figsize=(18, 6.4), constrained_layout=True)
        display_name = "Time-block-constrained" if tree_name == "time_prior" else "Unconstrained"
        plot_tree(tree_axis, root, label=(f"{display_name} SPT | "
                  f"seed {seed}, {state.replace('_', ' ')} | joint-target affine Xi = {root.xi_bits:.2f} bits"),
                  zone_ids=zone_ids, norm=norm)
        handles = [mpl.lines.Line2D([], [], marker="o", ls="", ms=4, color=color, label=name)
                   for name, color in TIME_COLORS.items()]
        figure.legend(handles=handles, loc="outside upper center", ncol=3, frameon=False,
                      title="Source atom time scale")
        colorbar = figure.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap="YlGnBu"),
                                   ax=tree_axis, fraction=.018, pad=.015, aspect=35)
        colorbar.set_ticks([0, .001, .01, .1, 1, 10], labels=["0", ".001", ".01", ".1", "1", "10"])
        colorbar.set_label("Local Syn (bits; logarithmic color above .001)")
        path = FIG_DIR / f"nyc_taxi_mgstn_spt_{suffix}.png"
        figure.savefig(path, dpi=400, bbox_inches="tight")
        plt.close(figure)
        outputs.append(path)
    return outputs


def aggregate_summary(summaries: Sequence[dict], validations: Sequence[dict], figures: Sequence[Path]) -> dict:
    if any(payload.get("status") != "passed" for payload in validations):
        raise RuntimeError("Cannot aggregate failed or incomplete quadratic audits")
    rows = {}
    for tree_name in ("unconstrained", "time_prior"):
        metrics = [tree_metrics(deserialize_tree(summary[tree_name]["tree"])) for summary in summaries]
        rows[tree_name] = {
            key: {
                "mean": float(np.mean([row[key] for row in metrics])),
                "sd": float(np.std([row[key] for row in metrics], ddof=1)) if len(metrics) > 1 else 0.,
                "minimum": float(min(row[key] for row in metrics)),
                "maximum": float(max(row[key] for row in metrics)),
            }
            for key in metrics[0]
        }
    validation_records = [record for payload in validations for record in payload["records"]]
    return {
        "status": "complete_affine_and_projected_diagnostics" if validations else "complete_affine_only",
        "conditions": len(summaries),
        "comparison": "only the allowed SPT partition structure changes",
        "affine_search": rows,
        "joint_target_xi_bits": [summary["unconstrained"]["tree"]["xi_bits"] for summary in summaries],
        "affine_search_seconds": [summary["elapsed_seconds"] for summary in summaries],
        "maximum_absolute_closure_error_bits": max(abs(summary[name]["closure_error_bits"])
            for summary in summaries for name in ("unconstrained", "time_prior")),
        "representative_condition": representative_condition(summaries),
        "quadratic_validation": {
            "record_count": len(validation_records),
            "minimum_zone_syn_bits": float(min(record["quadratic_min_zone_bits"] for record in validation_records)) if validation_records else None,
            "node_with_any_violation_count": int(sum(record["quadratic_violation_zone_count"] > 0 for record in validation_records)),
            "tolerance_negative_count": sum(record["quadratic_negative_zone_count"] for record in validation_records),
            "targetwise_estimate_count_including_reused_splits": sum(len(record["zone_values_bits"]) for record in validation_records),
            "interpretation": "Projected target-wise CMI checks only; not full joint-target tree validation or an independent confirmation set",
            "tolerance_bits": QUADRATIC_TOLERANCE_BITS,
        },
        "figures": [str(path.relative_to(ROOT)) for path in figures],
    }


def main() -> None:
    global RUN_DIR, ACTIVE_PROGRESS
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=4096)
    parser.add_argument("--components", type=int, default=2)
    parser.add_argument("--model-seeds", type=int, nargs="+", default=list(DEFAULT_SEEDS))
    parser.add_argument("--states", nargs="+", default=list(DEFAULT_STATES))
    parser.add_argument("--target-ridge", type=float, default=1.0e-6)
    parser.add_argument("--quadratic-ridge", type=float, default=1.0e-6)
    parser.add_argument("--exact-max-size", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=512)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--skip-quadratic", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()
    if args.smoke:
        args.model_seeds = [args.model_seeds[0]]
        args.states = [args.states[0]]
    if args.components != 2:
        parser.error("This registered experiment uses exactly two PCs per atom")
    RUN_DIR = OUTPUT_DIR / (f"affine_regression_v3_time_block_search_n{args.samples}_pc{args.components}"
                            f"_r{args.target_ridge:g}_exact{args.exact_max_size}")

    conditions = [(seed, state) for seed in args.model_seeds for state in args.states]
    total = 1 + 2 * len(conditions) + (0 if args.skip_quadratic else len(conditions)) + 1
    progress = Progress(total)
    ACTIVE_PROGRESS = progress
    progress.write("initializing", force=True)
    training = load_module(TRAIN_SCRIPT, "nyc_taxi_training_spt")
    ei = load_module(EI_SCRIPT, "nyc_taxi_ei_spt")
    quadratic = FastQuadraticTM
    data, prepared, split = training.load_data(False)

    try:
        intervention = prepare_shared_intervention(
            training, data, prepared, split, samples=args.samples, components=args.components,
            smoke=args.smoke,
        )
        progress.advance("intervention", metrics={"samples": args.samples, "atoms": 198})
        device = ei.choose_device(args.device)
        targets = {}
        for seed, state in tqdm(conditions, desc="MGSTN joint interventions", unit="condition"):
            targets[(seed, state)] = predict_targets(
                training, ei, data, prepared, split, intervention, seed=seed, state=state,
                device=device, batch_size=args.batch_size,
            )
            progress.advance("mgstn_targets", metrics={"seed": seed, "state": state, "device": str(device)})

        summaries = []
        for seed, state in tqdm(conditions, desc="Affine SPT", unit="tree-pair"):
            summary = run_affine_condition(
                intervention, targets[(seed, state)], seed=seed, state=state,
                target_ridge=args.target_ridge,
                exact_max_size=args.exact_max_size,
            )
            summaries.append(summary)
            progress.advance(
                "affine_spt",
                metrics={"seed": seed, "state": state,
                         "mixed_candidates": summary["unconstrained"]["candidate_split_count"],
                         "prior_candidates": summary["time_prior"]["candidate_split_count"]},
            )

        figures = plot_figures(summaries, conditions)
        validations = []
        if not args.skip_quadratic:
            for summary in tqdm(summaries, desc="Quadratic split validation", unit="condition"):
                seed, state = int(summary["seed"]), str(summary["state"])
                validation = validate_quadratic_condition(
                    intervention, targets[(seed, state)], summary, quadratic,
                    seed=seed, state=state, ridge=args.quadratic_ridge,
                    tree_names=("unconstrained", "time_prior"),
                )
                validations.append(validation)
                progress.advance(
                    "quadratic_validation",
                    metrics={"seed": seed, "state": state,
                             "records": len(validation["records"]),
                             "violating_nodes": validation["node_with_any_violation_count"]},
                )

        aggregate = aggregate_summary(summaries, validations, figures)
        suffix = "smoke" if args.smoke else "summary"
        atomic_json(RUN_DIR / f"{suffix}.json", aggregate)
        progress.advance("complete", metrics={"summary": str(RUN_DIR / f"{suffix}.json")})
        progress.write("complete", metrics={"summary": str(RUN_DIR / f"{suffix}.json")}, force=True)
        print(json.dumps(aggregate, ensure_ascii=False, indent=2))
    except Exception as error:
        progress.write("failed", message=str(error), force=True)
        raise


if __name__ == "__main__":
    with threadpool_limits(limits=1):
        main()
