#!/usr/bin/env python3
"""Plot the processed 83-ROI proxy coupling matrix used by the DMF analysis.

Figure contract
---------------
Core conclusion: the matrix used by the 83-ROI DMF experiment is a directed,
moderately dense F-TRACT CCEP-support proxy with visible anatomical blocks; it
is not an HCP diffusion-MRI fiber matrix.
Archetype: quantitative grid (single hero heatmap).
Backend/output: Python/matplotlib; 183-mm SVG plus PNG preview.
Source data: the labeled ``count_00_connectivity.csv`` generated by dmf_fig6.py.
Reviewer risks: directionality and nonlinear display normalization are stated
explicitly in the axis labels and colorbar note.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap, PowerNorm


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = (
    ROOT / "exp" / "brain" / "result_lausanne_fig6" / "count_00_connectivity.csv"
)
DEFAULT_OUTPUT = ROOT / "fig" / "dmf_83roi_proxy_connectivity_matrix"

GROUPS = (
    ("Left cortex", 34, "#4C78A8"),
    ("Left subcortex", 7, "#72B7B2"),
    ("Right cortex", 34, "#D88989"),
    ("Right subcortex", 7, "#A47BB5"),
    ("Brainstem", 1, "#767676"),
)


def load_labeled_matrix(path: Path) -> tuple[list[str], np.ndarray]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.reader(handle))

    labels = [row[0] for row in rows]
    matrix = np.asarray([[float(value) for value in row[1:]] for row in rows])
    if matrix.shape != (83, 83) or len(labels) != 83:
        raise ValueError(f"Expected an 83x83 labeled matrix, got {matrix.shape}.")
    if not np.isfinite(matrix).all() or np.any(matrix < 0):
        raise ValueError("Connectivity must contain only finite, non-negative values.")
    return labels, matrix


def group_geometry() -> tuple[np.ndarray, np.ndarray, list[str], list[str]]:
    sizes = np.asarray([size for _, size, _ in GROUPS])
    boundaries = np.concatenate(([0], np.cumsum(sizes)))
    centers = (boundaries[:-1] + boundaries[1:]) / 2 - 0.5
    labels = [name for name, _, _ in GROUPS]
    colors = [color for _, _, color in GROUPS]
    return boundaries, centers, labels, colors


def configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "font.size": 7,
            "axes.linewidth": 0.8,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
        }
    )


def plot_connectivity(matrix: np.ndarray, output_stem: Path) -> None:
    configure_style()
    boundaries, centers, group_labels, group_colors = group_geometry()

    cmap = LinearSegmentedColormap.from_list(
        "ftract_blue",
        ["#FFFFFF", "#DCE9F3", "#9DBDD7", "#4C78A8", "#174A78", "#272727"],
    )
    norm = PowerNorm(gamma=0.45, vmin=0.0, vmax=float(matrix.max()))

    fig = plt.figure(figsize=(7.2, 6.1), constrained_layout=True)
    grid = fig.add_gridspec(
        nrows=2,
        ncols=3,
        width_ratios=(0.035, 1.0, 0.055),
        height_ratios=(0.035, 1.0),
        wspace=0.035,
        hspace=0.035,
    )
    ax_top = fig.add_subplot(grid[0, 1])
    ax_left = fig.add_subplot(grid[1, 0])
    ax = fig.add_subplot(grid[1, 1])
    cax = fig.add_subplot(grid[1, 2])

    image = ax.imshow(
        matrix,
        cmap=cmap,
        norm=norm,
        interpolation="nearest",
        aspect="equal",
        origin="upper",
    )

    for boundary in boundaries[1:-1]:
        location = boundary - 0.5
        ax.axhline(location, color="white", linewidth=0.8, alpha=0.95)
        ax.axvline(location, color="white", linewidth=0.8, alpha=0.95)

    ax.set_xticks(centers)
    ax.set_xticklabels(group_labels, rotation=36, ha="left", rotation_mode="anchor")
    ax.xaxis.tick_top()
    ax.set_yticks(centers)
    ax.set_yticklabels(group_labels)
    ax.tick_params(axis="both", which="both", length=0, pad=4, colors="#333333")
    ax.set_xlabel("Recorded ROI (F-TRACT column)", labelpad=8)
    ax.set_ylabel("Stimulated ROI (F-TRACT row)", labelpad=8)
    for spine in ax.spines.values():
        spine.set_visible(False)

    group_codes = np.concatenate(
        [np.full(size, index) for index, (_, size, _) in enumerate(GROUPS)]
    )
    strip_cmap = mpl.colors.ListedColormap(group_colors)
    strip_norm = mpl.colors.BoundaryNorm(np.arange(len(GROUPS) + 1) - 0.5, len(GROUPS))
    ax_top.imshow(
        group_codes[np.newaxis, :],
        cmap=strip_cmap,
        norm=strip_norm,
        aspect="auto",
        interpolation="nearest",
    )
    ax_left.imshow(
        group_codes[:, np.newaxis],
        cmap=strip_cmap,
        norm=strip_norm,
        aspect="auto",
        interpolation="nearest",
    )
    for strip_ax in (ax_top, ax_left):
        strip_ax.set_axis_off()

    colorbar = fig.colorbar(image, cax=cax)
    colorbar.set_label("DMF coupling weight, $C_{jk}$", labelpad=7)
    colorbar.set_ticks([0.00, 0.02, 0.04, 0.06, 0.08, 0.10])
    colorbar.ax.tick_params(length=2.5, width=0.6)
    colorbar.outline.set_linewidth(0.6)
    colorbar.ax.text(
        0.5,
        -0.055,
        "Power scale\n($\\gamma=0.45$)",
        ha="center",
        va="top",
        transform=colorbar.ax.transAxes,
        fontsize=6.2,
        color="#4D4D4D",
    )

    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_stem.with_suffix(".svg"), bbox_inches="tight")
    fig.savefig(output_stem.with_suffix(".png"), dpi=300, bbox_inches="tight")
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    _, matrix = load_labeled_matrix(args.input)
    plot_connectivity(matrix, args.output)
    print(f"matrix_shape={matrix.shape}")
    print(f"nonzero_edges={np.count_nonzero(matrix)}")
    print(f"density={np.count_nonzero(matrix) / (83 * 82):.6f}")
    print(f"weight_range=[{matrix.min():.10f}, {matrix.max():.10f}]")
    print(f"weight_sum={matrix.sum():.10f}")
    print(f"saved={args.output.with_suffix('.svg')}")
    print(f"saved={args.output.with_suffix('.png')}")


if __name__ == "__main__":
    main()
