"""Validate the shared greedy Phi hierarchy on planted Boolean dynamics.

The maximum-entropy intervention samples five independent binary sources.  The
two target coordinates are generated by a three-source XOR and a two-source
XOR, respectively.  Their population EI table is analytic, so the empirical
EI estimator and the hierarchy can both be checked against ground truth.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
import sys
from pathlib import Path
from typing import Iterable, Mapping, Sequence

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.phi_hierarchy import NONNEGATIVE_TOLERANT, PhiAtom, greedy_phi_atoms, subset_phi_raw


SOURCES = ("X1", "X2", "X3", "X4", "X5")
PLANTED_MODULES = (("X1", "X2", "X3"), ("X4", "X5"))
DEFAULT_RESULT = ROOT / "results" / "greedy_hierarchy_known_dynamics" / "summary.json"
DEFAULT_FIGURE = ROOT / "docs" / "ref" / "assets" / "greedy_hierarchy_known_dynamics" / "validation"


def all_subsets() -> list[tuple[str, ...]]:
    return [combo for size in range(1, len(SOURCES) + 1) for combo in itertools.combinations(SOURCES, size)]


def binary_entropy(probability: float) -> float:
    q = float(probability)
    if q <= 0.0 or q >= 1.0:
        return 0.0
    return float(-q * math.log2(q) - (1.0 - q) * math.log2(1.0 - q))


def oracle_ei_table(noise: float) -> dict[tuple[str, ...], float]:
    """Population EI under independent Bernoulli(1/2) interventions."""
    capacity = 1.0 - binary_entropy(noise)
    table: dict[tuple[str, ...], float] = {}
    for subset in all_subsets():
        members = set(subset)
        table[subset] = float(capacity * sum(set(module).issubset(members) for module in PLANTED_MODULES))
    return table


def generate_data(sample_count: int, noise: float, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Generate source/target samples from the known transition mechanism."""
    rng = np.random.default_rng(seed)
    source = rng.integers(0, 2, size=(int(sample_count), len(SOURCES)), dtype=np.int8)
    target = np.column_stack(
        (
            source[:, 0] ^ source[:, 1] ^ source[:, 2],
            source[:, 3] ^ source[:, 4],
        )
    ).astype(np.int8)
    if noise > 0.0:
        target ^= (rng.random(target.shape) < float(noise)).astype(np.int8)
    return source, target


def encode_binary_columns(values: np.ndarray, columns: Iterable[int]) -> np.ndarray:
    indices = tuple(int(index) for index in columns)
    weights = (1 << np.arange(len(indices), dtype=np.int64))
    return np.asarray(values[:, indices], dtype=np.int64) @ weights


def mutual_information(source_code: np.ndarray, target_code: np.ndarray) -> float:
    source_code = np.asarray(source_code, dtype=np.int64)
    target_code = np.asarray(target_code, dtype=np.int64)
    source_levels = int(source_code.max()) + 1
    target_levels = int(target_code.max()) + 1
    joint = np.bincount(
        source_code * target_levels + target_code,
        minlength=source_levels * target_levels,
    ).reshape(source_levels, target_levels).astype(float)
    joint /= float(joint.sum())
    px = joint.sum(axis=1, keepdims=True)
    py = joint.sum(axis=0, keepdims=True)
    independent = px @ py
    mask = joint > 0.0
    return float(np.sum(joint[mask] * np.log2(joint[mask] / independent[mask])))


def empirical_ei_table(source: np.ndarray, target: np.ndarray) -> dict[tuple[str, ...], float]:
    target_code = encode_binary_columns(target, (0, 1))
    name_to_index = {name: index for index, name in enumerate(SOURCES)}
    return {
        subset: mutual_information(
            encode_binary_columns(source, (name_to_index[name] for name in subset)),
            target_code,
        )
        for subset in all_subsets()
    }


def decompose(table: Mapping[tuple[str, ...], float]) -> list[PhiAtom]:
    return greedy_phi_atoms(
        SOURCES,
        table,
        policy=NONNEGATIVE_TOLERANT,
        eps=1.0e-8,
        split_tolerance=2.0e-2,
    )


def summarize_run(sample_count: int, noise: float, seed: int, *, shuffle_target: bool = False) -> dict[str, object]:
    source, target = generate_data(sample_count, noise, seed)
    if shuffle_target:
        target = target[np.random.default_rng(seed + 100_003).permutation(len(target))]
    empirical = empirical_ei_table(source, target)
    oracle = oracle_ei_table(noise)
    atoms = decompose(empirical)
    root_phi = subset_phi_raw(SOURCES, empirical)
    positive_atoms = [atom for atom in atoms if atom.value > 0.0]
    ranked = sorted(positive_atoms, key=lambda atom: atom.value, reverse=True)
    top_two = {atom.sources for atom in ranked[:2]}
    planted = set(PLANTED_MODULES)
    planted_mass = sum(atom.value for atom in positive_atoms if atom.sources in planted)
    total_mass = sum(atom.value for atom in positive_atoms)
    return {
        "sample_count": int(sample_count),
        "noise": float(noise),
        "seed": int(seed),
        "shuffle_target": bool(shuffle_target),
        "subset_ei_rmse_bits": float(
            np.sqrt(np.mean([(empirical[key] - oracle[key]) ** 2 for key in oracle]))
        ),
        "phi_empirical_bits": float(root_phi),
        "phi_oracle_bits": float(2.0 * (1.0 - binary_entropy(noise))),
        "closure_error_bits": float(sum(atom.value for atom in atoms) - root_phi),
        "top2_exact_recovery": bool(top_two == planted),
        "planted_atom_mass_fraction": float(planted_mass / total_mass) if total_mass > 0.0 else 0.0,
        "atoms": [
            {
                "sources": list(atom.sources),
                "value_bits": float(atom.value),
                "kind": atom.kind,
                "depth": int(atom.depth),
            }
            for atom in ranked
        ],
        "empirical_ei_bits": {"+".join(key): float(value) for key, value in empirical.items()},
        "oracle_ei_bits": {"+".join(key): float(value) for key, value in oracle.items()},
    }


def aggregate_runs(runs: Sequence[Mapping[str, object]]) -> dict[str, float]:
    return {
        "n_runs": int(len(runs)),
        "top2_exact_recovery_rate": float(np.mean([row["top2_exact_recovery"] for row in runs])),
        "mean_planted_atom_mass_fraction": float(np.mean([row["planted_atom_mass_fraction"] for row in runs])),
        "mean_subset_ei_rmse_bits": float(np.mean([row["subset_ei_rmse_bits"] for row in runs])),
        "max_abs_closure_error_bits": float(np.max(np.abs([row["closure_error_bits"] for row in runs]))),
    }


def build_summary(seeds: Sequence[int]) -> dict[str, object]:
    sample_counts = (512, 2048, 8192)
    noise_levels = (0.0, 0.05, 0.15)
    representative = summarize_run(32768, 0.05, int(seeds[0]))
    grid: dict[str, dict[str, float]] = {}
    all_runs: list[dict[str, object]] = []
    for sample_count in sample_counts:
        for noise in noise_levels:
            condition = [summarize_run(sample_count, noise, int(seed)) for seed in seeds]
            all_runs.extend(condition)
            grid[f"n={sample_count},q={noise:.2f}"] = aggregate_runs(condition)
    shuffled = [summarize_run(8192, 0.05, int(seed), shuffle_target=True) for seed in seeds]
    observed = [row for row in all_runs if row["sample_count"] == 8192 and row["noise"] == 0.05]
    return {
        "experiment_contract": {
            "question": "Can empirical EI plus the shared greedy hierarchy recover planted dynamical terms?",
            "sources": "five independent Bernoulli(1/2) maximum-entropy interventions",
            "dynamics": ["Y1 = X1 XOR X2 XOR X3 XOR E1", "Y2 = X4 XOR X5 XOR E2"],
            "estimator": "discrete plug-in EI; TM is inapplicable to binary state spaces",
            "primary_metric": "exact recovery of both planted modules among the two largest atoms",
            "secondary_metrics": ["planted atom mass fraction", "subset-EI RMSE", "hierarchy closure error"],
            "paired_unit": "seed shared across sample-count and noise conditions",
        },
        "representative": representative,
        "robustness_grid": grid,
        "negative_control": {
            "observed_n8192_q005": aggregate_runs(observed),
            "shuffled_target_n8192_q005": aggregate_runs(shuffled),
            "mean_observed_phi_bits": float(np.mean([row["phi_empirical_bits"] for row in observed])),
            "mean_shuffled_phi_bits": float(np.mean([row["phi_empirical_bits"] for row in shuffled])),
        },
    }


def configure_plotting() -> None:
    mpl.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
            "font.size": 7,
            "axes.spines.right": False,
            "axes.spines.top": False,
            "axes.linewidth": 0.8,
            "legend.frameon": False,
            "svg.fonttype": "none",
            "pdf.fonttype": 42,
        }
    )


def plot_summary(summary: Mapping[str, object], figure_base: Path) -> None:
    configure_plotting()
    representative = summary["representative"]
    grid = summary["robustness_grid"]
    figure, axes = plt.subplots(1, 4, figsize=(7.2, 2.05), constrained_layout=True)

    membership = np.array([[1, 1, 1, 0, 0], [0, 0, 0, 1, 1]], dtype=float)
    axes[0].imshow(membership, cmap=mpl.colors.ListedColormap(["#F2F2F2", "#4477AA"]), vmin=0, vmax=1)
    axes[0].set_xticks(range(5), SOURCES)
    axes[0].set_yticks((0, 1), (r"$Y_1$ (3-XOR)", r"$Y_2$ (2-XOR)"))
    axes[0].set_xlabel("Intervened source")
    for row in range(2):
        for column in range(5):
            axes[0].text(column, row, "×" if membership[row, column] else "", ha="center", va="center", color="white", fontsize=8)

    oracle_values = np.array(list(representative["oracle_ei_bits"].values()), dtype=float)
    empirical_values = np.array(list(representative["empirical_ei_bits"].values()), dtype=float)
    axes[1].scatter(oracle_values, empirical_values, s=14, color="#4477AA", alpha=0.80, edgecolor="none")
    limit = max(2.02, float(max(oracle_values.max(), empirical_values.max()) * 1.03))
    axes[1].plot((0, limit), (0, limit), color="0.35", lw=0.8, ls="--")
    axes[1].set(xlabel="Population EI (bits)", ylabel="Empirical EI (bits)", xlim=(-0.04, limit), ylim=(-0.04, limit))
    axes[1].text(0.05, 0.92, f"RMSE = {representative['subset_ei_rmse_bits']:.3f} bits", transform=axes[1].transAxes)

    empirical_atoms = {tuple(row["sources"]): float(row["value_bits"]) for row in representative["atoms"]}
    capacity = 1.0 - binary_entropy(float(representative["noise"]))
    labels = ("3-XOR\n$X_1X_2X_3$", "2-XOR\n$X_4X_5$", "Other")
    empirical_bars = (
        empirical_atoms.get(PLANTED_MODULES[0], 0.0),
        empirical_atoms.get(PLANTED_MODULES[1], 0.0),
        sum(value for key, value in empirical_atoms.items() if key not in set(PLANTED_MODULES)),
    )
    positions = np.arange(3)
    axes[2].bar(positions - 0.17, (capacity, capacity, 0.0), width=0.34, color="#BBBBBB", label="Population")
    axes[2].bar(positions + 0.17, empirical_bars, width=0.34, color="#EE7733", label="Empirical")
    axes[2].set_xticks(positions, labels)
    axes[2].set_ylabel("Greedy atom (bits)")
    axes[2].legend(loc="lower center", bbox_to_anchor=(0.5, 1.02), ncol=2)

    sample_counts = (512, 2048, 8192)
    noise_levels = (0.0, 0.05, 0.15)
    recovery = np.array(
        [[grid[f"n={sample_count},q={noise:.2f}"]["top2_exact_recovery_rate"] for sample_count in sample_counts] for noise in noise_levels]
    )
    image = axes[3].imshow(recovery, vmin=0.0, vmax=1.0, cmap="Blues", aspect="auto")
    axes[3].set_xticks(range(3), ("512", "2,048", "8,192"))
    axes[3].set_yticks(range(3), ("0", "0.05", "0.15"))
    axes[3].set(xlabel="Samples", ylabel="Bit-flip probability")
    for row in range(3):
        for column in range(3):
            value = recovery[row, column]
            axes[3].text(column, row, f"{value:.0%}", ha="center", va="center", color="white" if value > 0.55 else "black")
    colorbar = figure.colorbar(image, ax=axes[3], fraction=0.050, pad=0.04)
    colorbar.set_label("Exact top-2 recovery")

    for label, axis in zip("abcd", axes):
        axis.text(-0.18, 1.08, label, transform=axis.transAxes, fontsize=8, fontweight="bold", va="top")

    figure_base.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(figure_base.with_suffix(".png"), dpi=600, bbox_inches="tight")
    figure.savefig(figure_base.with_suffix(".svg"), bbox_inches="tight")
    figure.savefig(figure_base.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(figure)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=int, default=12, help="Number of paired robustness seeds.")
    parser.add_argument("--result", type=Path, default=DEFAULT_RESULT)
    parser.add_argument("--figure-base", type=Path, default=DEFAULT_FIGURE)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    summary = build_summary(tuple(range(int(args.seeds))))
    args.result.parent.mkdir(parents=True, exist_ok=True)
    args.result.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    plot_summary(summary, args.figure_base)
    representative = summary["representative"]
    print(f"Top-2 planted modules recovered: {representative['top2_exact_recovery']}")
    print(f"Planted atom mass: {representative['planted_atom_mass_fraction']:.4f}")
    print(f"Subset-EI RMSE: {representative['subset_ei_rmse_bits']:.4f} bits")
    print(f"Saved result: {args.result}")
    print(f"Saved figure: {args.figure_base}.{{png,svg,pdf}}")


if __name__ == "__main__":
    main()
